name: dev 環境の掃除

run-name: dev 環境の掃除

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  cleanup_1:
    runs-on: ubuntu-latest
    name: 掃除 その1
    steps:
      - run: |
          echo "cleaning..."
          echo "cleaning..."
          echo "cleaning..."
