name: deploy-stg

# main branch に push されたら staging 環境に deploy する
on:
  push:
    branches:
      - main

concurrency:
  group: deploy-stg
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    strategy:
      matrix:
        service-name: [frontend, hosting]
    with:
      workload-identity-provider: projects/123/locations/global/workloadIdentityPools/pool/providers/gha
      service-account: myaccount
      env: stg
      service-name: ${{ matrix.service-name }}
