name: deploy-prd

# tag が push されたら production 環境に deploy する
# tag の naming rule があれば条件を合わせる
on:
  push:
    tags:
      - '*'

concurrency:
  group: deploy-prd
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to production
    uses: ./.github/workflows/reusable-deploy.yml
    strategy:
      matrix:
        service-name: [frontend, hosting]
    with:
      workload-identity-provider: projects/123/locations/global/workloadIdentityPools/pool/providers/gha
      service-account: myaccount
      env: prd
      service-name: ${{ matrix.service-name }}
