name: main branch への Pull Request

#run-name: "${{ github.workflow }} by @${{ github.actor }}"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  lint:
    name: lint 1
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: lint step 1
        run: |
          echo "lint 1"

  test:
    name: test 1
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: test step 1
        run: |
          echo "step 1"

      - name: test step 2
        run: |
          echo "step 2"

      - name: test step 3
        run: |
          echo "step 3"
