name: dev 環境への deploy

run-name: "${{ github.workflow }} by @${{ github.actor }} (${{ github.ref }})"

on:
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop

  push:
    branches:
      - develop

concurrency:
  group: deploy-develop
  cancel-in-progress: false

jobs:
  test:
    name: test 1
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: test step 1
        run: |
          echo "step 1"

  deploy:
    name: dev 環境への deploy
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - run: |
          echo "deploy 中..."
          sleep 1
          echo "deploy 中..."
          sleep 1
          echo "deploy 中..."
          sleep 1
          echo "deploy 完了"

  debug:
    name: debug
    runs-on: ubuntu-latest
    needs:
      - test
      - deploy
    if: ${{ failure() }}
    steps:
      - run: |
          echo "debug"

  cleanup:
    name: cleanup
    runs-on: ubuntu-latest
    needs:
      - test
      - deploy
    steps:
      - run: |
          echo "後片付け中"
          sleep 2
          echo "後片付け中"
          sleep 2
          echo "後片付け中"
          sleep 2
          echo "後片付け中"
          sleep 2
          echo "後片付け中"
          sleep 2
          echo "完了"
