name: test

# main branch への Pull Request 時に実行
on:
  workflow_run:
    workflows:
      - git-pr-release
    types:
      - completed

jobs:
  test:
    name: Test
    uses: ./.github/workflows/reusable-test.yml
