name: My Main Branch Workflow Name

run-name: "Customized Run Name for ${{ github.workflow }} by @${{ github.actor }}"

on:
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

  push:
    branches:
      - main

jobs:
  job 1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: test step 1
        run: |
          echo "step 1"

      - name: test step 2
        run: |
          echo "step 2"

      - name: test step 3
        run: |
          echo "step 3"

  job 2:
    name: Job 2
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: test step 1
        run: |
          echo "step 1"

      - name: test step 2
        run: |
          echo "step 2"

      - name: test step 3
        run: |
          echo "step 3"
