name: reusable-test

on:
  workflow_call:
    inputs:
      skip:
        description: 'skip test if true'
        type: boolean
        default: false

jobs:
  test:
    if: inputs.skip == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.5
      - name: sleep 1
        run: |
          echo "::group::my group"
          echo "begin sleep"
          sleep 2
          echo "end sleep"
          echo "::endgroup::"
          echo "sleep 1 step 終わったよ" >> $GITHUB_STEP_SUMMARY
      - name: sleep 2
        run: |
          sleep 2
          echo "sleep 2 step 終わったよ" >> $GITHUB_STEP_SUMMARY
